### ISSUE TITLE
Fallback to EN translations

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode-nls#15]
**Case:** Extension is providing a translation file (i.e. `package.nls.ja.json`) but the values of the `json` are empty strings.
**Issue:** Message shows the key, not the value. 
**Solution:** Fallback to `EN` translations instead of displaying the key.
![screenshot - 26_10_2017 11_56_04](https://user-images.githubusercontent.com/1716442/32043903-b365c0ac-ba44-11e7-9dfd-12ea3a5cb8a5.png)

@dbaeumer Are we interested in the proposed solution? Will you be accepting a PR for this?

**Comment by dbaeumer** [comment]
The fallback should happen during build time not during runtime since it unnecessarily requires lookup resources. This is what we do at least for all JS files and the corresponding nls files. During build time of the nls packages we replace missing strings with the English value.

However such a build time patching is not implemented for package.json files. I would accept a PR in vscode-nls-dev to do so.
